### ISSUE TITLE
Handle pagination

### ISSUE THREAD

**Issue by eloyrubinos** [nilsmehlhorn/ngx-observe#3]
I'm very intrigued by this module. I read about it in Dev.to and wanted to give it a try.

The only problem so far is that I'm not sure how to handle pagination. I have a GraphQL API and my observable returns an object similar to this:

 ```
projects: {
  edges: [{}],
  pageInfo: {},
  totalCount: number
 }
```
It's cursor based pagination so in essence I'd just have to swap the observable with a different API call that uses a different cursor. But how can I access the neccessary info (pageInfo and totalCount) outside the template to know what cursor I need?

**Comment by nilsmehlhorn** [comment]
I'd need more information about your setup, the object you're providing doesn't really show the type you're dealing with. However, the ngx-observe directive deals only with rendering of observables into the view. Your problem is probably the composition of the observable you want to render and not really with this directive.

I recentely wrote an article describing [how to create a paginated datasource for Angular Material](https://nils-mehlhorn.de/posts/angular-material-pagination-datasource). This also yielded the library [nilsmehlhorn/ngx-pagination-data-source](https://github.com/nilsmehlhorn/ngx-pagination-data-source). If you're using Angular Material, this might help you out. Otherwise, you can apply the concepts from the article to your situation.

You basically want to compose an observable starting with the parameters you need for retrieving a page (number, size, sort), then [switchMap](https://rxjs-dev.firebaseapp.com/api/operators/switchMap) into an HTTP/GraphQL request, eventually providing the page to your view, thus ngx-observe.

**Comment by eloyrubinos** [comment]
That article will help a lot, thank you :) It doesn't apply exactly but close enough that I get how to do it. Great article by the way :)
